### ISSUE TITLE
better error handling when trying to destroy a disconnected environment.

### ISSUE THREAD

**Issue by Elmo33** [Altinity/terraform-provider-altinitycloud#63]
if environment is disconnected for any specific reason and the user runs 'terraform destroy' no resources are actually removed/destroyed, but the env is moved to 'pending deletion' state. 

Since no resources are able to be removed due to disconnection, then it would make sense to add some kind of warning for the user that the env is disconnected and there is no point to run terraform destroy and eventually environment shouldnt be moved to 'pending deletion' state either.

**Comment by Elmo33** [comment]
I faced this issue when I ran the terraform destroy, while reconciler hadnt finished and the env was not connected. But it could happen for any other reason.

**Comment by ianaya89** [comment]
Fixed https://github.com/Altinity/terraform-provider-altinitycloud/commit/db5f17e9f6ce2f7106c041d3afee42a82166fe63
