### ISSUE TITLE
number_of_zones is calculated automatically in environments tfstate, but is null in data source

### ISSUE THREAD

**Issue by Elmo33** [Altinity/terraform-provider-altinitycloud#68]
If I create an environment in AWS BYOC (haven't checked other env types yet), and set zones to  
```zones = ["us-east-1a", "us-east-1b"]``` tfstate will automatically calculate and fill the number_of_zones variable and set it to 2.

but when I use data source to retrieve the environment data, its set to null.

we either have to set it to null initially, since the user is not actually specifying that var, or if its necessary to be there, then data source also should do the same calculation.

**Comment by ianaya89** [comment]
When you create resources there are computed values (like an id), so it's not a problem that the user didn't specify it but it should match whatever we as zones length.

**Comment by ianaya89** [comment]
`number_of_zones` will be deprecated soon

#116
