### ISSUE TITLE
Q - adding checks to the terraform config structure

### ISSUE THREAD

**Issue by Elmo33** [Altinity/terraform-provider-altinitycloud#73]
for both environment config and eks-clickhouse config, there are too many ways users can mess up the config that can be detected with structure simple checks.

We need to discuss if its possible to somehow apply those checks before starting provisioning any kind of resources.

**Comment by ianaya89** [comment]
- `eks-clickhouse` it's a module, there is no thing as running checks there. It's a just a set of existing terraform code put together 
- The provider it's different but would be great to have listed things that we want to change. Unless is strictly needed to add them here, those checks will be part of the Anyhere API
