### ISSUE TITLE
wrong error when env zones list is empty

### ISSUE THREAD

**Issue by Elmo33** [Altinity/terraform-provider-altinitycloud#77]
if zones attribute is set to an empty list terraform returns this error:
```
│ Attribute zones list must contain at least 1 elements, got: 0
```
the issue is that min limit is 2, so if the user sets empty list it should return:
```
│ Attribute zones list must contain at least 2 elements, got: 0
```
and if they set to 1 it should still return:
```
│ Attribute zones list must contain at least 2 elements, got: 1
```

**Comment by ianaya89** [comment]
Already fixed https://github.com/Altinity/terraform-provider-altinitycloud/commit/dd77f533e7092d78271d1c98fa370082c4cd290d
