### ISSUE TITLE
add invalid attribute value type handling for node group name and type

### ISSUE THREAD

**Issue by Elmo33** [Altinity/terraform-provider-altinitycloud#83]
disallow any values for these two attributes that are not a string.

**Comment by Elmo33** [comment]
this error is shown when name is string and type is list

╷
│ Error: Incorrect attribute value type
│
│   on main.tf line 35, in resource "altinitycloud_env_aws" "this":
│   35:   node_groups = [{"name": ["t4.large"], "node_type": ["t4.large"], "capacity_per_zone": 1, "reservations": ["CLICKHOUSE", "SYSTEM", "ZOOKEEPER"]}]
│
│ Inappropriate value for attribute "node_groups": element 0: attribute "name": string required.
╵

but doesnt show in any other cases (that ive checked: int, string, int int, list list)

**Comment by ianaya89** [comment]
This is expected because is how Terraform's HCL tends to coerce values to match expected types whenever is possible.
`int and bool` can ve casted to strings but `list` cannot.

> [Docs](https://developer.hashicorp.com/terraform/language/expressions/type-constraints#conversion-of-primitive-types)
