### ISSUE TITLE
its possible to change the region if the env is not fully provisioned

### ISSUE THREAD

**Issue by Elmo33** [Altinity/terraform-provider-altinitycloud#85]
scenario:
1. I create env with 3 azs for a region that has no 3azs (could be any az related invalid value)
2. terraform returns the error that env cant be created, but meanwhile altinity-connect VPC is created
3. I change the region for both provider and module and try to provision.
4. provisioning is possible, (despite other resources in the previous region)
5. I deprovision the env with terraform destroy
6. destroy is finished, but the initial resources in region 1, are still orphaned.

**Comment by ianaya89** [comment]
Moved to https://github.com/Altinity/terraform-altinitycloud-connect-aws/issues/1
